# CloudFormation output name: `sls-${SERVICE_NAME}-${STAGE}`
service: sls-${self:custom.service}

package:
  # Limit files we will send up to Lambda.
  # https://serverless.com/framework/docs/providers/aws/guide/packaging/
  #
  # AWS constraints:
  # https://docs.aws.amazon.com/lambda/latest/dg/limits.html#limits-list
  # - Zipped bundle: `50 MB`
  # - Unzipped bundle: `250 MB`
  #
  # TODO: Write a custom packager (TODO_NEW_ISSUE)
  exclude:
    - "*"
    - "{aws,coverage,terraform,test}/**"
    - "**/node_modules/{.cache}/**"
    - "**/node_modules/aws-sdk/**" # included on Lambda.
    - "**/node_modules/.yarn-integrity"
    - "!package.json"

  # Serverless packages all our deps. We want to exclude the dev ones because
  # we have such a limited amount of space.
  excludeDevDependencies: true

custom:
  service: ${env:SERVICE_NAME}
  region: ${opt:region, env:AWS_REGION}
  stage: ${opt:stage, env:STAGE}

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  environment:
    STAGE: ${self:custom.stage}
    SERVICE_NAME: ${self:custom.service}
  # TODO: Replace default roll with custom one in CF.

functions:
  server:
    timeout: 30 # seconds (`300` max)
    memorySize: 128 # MB value (`1024` default)
    handler: src/server/index.handler
    events: # Use a generic proxy to allow Express app to route.
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    # TODO(Xray): Enable X-Ray tracing
    # Based on sls-generated CF template name.
    # ServerLambdaFunction:
    #   Properties:
    #     TracingConfig:
    #       Mode: Active
